/**
 * ScoreBreakdown Component
 *
 * Displays AI-generated category scores from analyzed reviews.
 * This is a Phase 3 feature — currently a stub/placeholder.
 *
 * Categories:
 * - Cinematography
 * - Plot
 * - Writing
 * - Characters
 * - Soundtrack
 * - Overall
 */

import React from "react";
import type { AiScores, ScoreCategory } from "@shared/types/movie";

interface ScoreBreakdownProps {
  scores: AiScores;
}

/**
 * Configuration for each score category
 */
const CATEGORY_CONFIG: Record<
  ScoreCategory,
  {
    label: string;
    icon: string;
    description: string;
  }
> = {
  cinematography: {
    label: "Cinematography",
    icon: "🎥",
    description: "Visual style, camera work, lighting",
  },
  plot: {
    label: "Plot",
    icon: "📖",
    description: "Story structure, pacing, engagement",
  },
  writing: {
    label: "Writing",
    icon: "✍️",
    description: "Dialogue, screenplay quality",
  },
  characters: {
    label: "Characters",
    icon: "🎭",
    description: "Character depth, development, performances",
  },
  soundtrack: {
    label: "Soundtrack",
    icon: "🎵",
    description: "Music, sound design, audio",
  },
  overall: {
    label: "Overall",
    icon: "⭐",
    description: "Combined assessment",
  },
};

/**
 * Score breakdown component
 */
const ScoreBreakdown: React.FC<ScoreBreakdownProps> = ({ scores }) => {
  // Order categories with "overall" last
  const orderedCategories: ScoreCategory[] = [
    "cinematography",
    "plot",
    "writing",
    "characters",
    "soundtrack",
    "overall",
  ];

  return (
    <div className="cb-space-y-3">
      <div className="cb-flex cb-items-center cb-gap-2 cb-mb-3">
        <span className="cb-text-lg">🤖</span>
        <span className="cb-text-white cb-font-medium cb-text-sm">
          AI Analysis
        </span>
        <span className="cb-text-gray-500 cb-text-xs">(beta)</span>
      </div>

      {orderedCategories.map((category) => {
        const score = scores[category];
        if (score === undefined) return null;

        return (
          <CategoryScore
            key={category}
            category={category}
            score={score}
            isOverall={category === "overall"}
          />
        );
      })}

      {/* Disclaimer */}
      <p className="cb-text-gray-500 cb-text-xs cb-mt-3 cb-pt-2 cb-border-t cb-border-surface-lighter">
        Scores generated by AI analysis of critic and audience reviews.
        Not an official rating.
      </p>
    </div>
  );
};

/**
 * Individual category score row
 */
const CategoryScore: React.FC<{
  category: ScoreCategory;
  score: number;
  isOverall?: boolean;
}> = ({ category, score, isOverall = false }) => {
  const config = CATEGORY_CONFIG[category];
  const colorClass = getScoreColor(score);

  return (
    <div
      className={`cb-flex cb-items-center cb-gap-3 ${
        isOverall ? "cb-pt-2 cb-border-t cb-border-surface-lighter" : ""
      }`}
    >
      {/* Icon */}
      <span className="cb-text-base" title={config.description}>
        {config.icon}
      </span>

      {/* Label and bar */}
      <div className="cb-flex-1">
        <div className="cb-flex cb-items-center cb-justify-between cb-mb-1">
          <span
            className={`cb-text-xs ${
              isOverall ? "cb-text-white cb-font-medium" : "cb-text-gray-400"
            }`}
          >
            {config.label}
          </span>
          <span className={`cb-text-sm cb-font-bold ${colorClass}`}>
            {score.toFixed(1)}
          </span>
        </div>

        {/* Score bar */}
        <div className="cb-w-full cb-h-1.5 cb-bg-surface-lighter cb-rounded-full cb-overflow-hidden">
          <div
            className={`cb-h-full cb-rounded-full cb-transition-all ${colorClass.replace(
              "cb-text-",
              "cb-bg-"
            )}`}
            style={{ width: `${(score / 10) * 100}%` }}
          />
        </div>
      </div>
    </div>
  );
};

/**
 * Get color class based on score (0-10 scale)
 */
function getScoreColor(score: number): string {
  if (score >= 7.5) {
    return "cb-text-green-400";
  } else if (score >= 5) {
    return "cb-text-yellow-400";
  } else {
    return "cb-text-red-400";
  }
}

export default ScoreBreakdown;
