/**
 * ScoreBreakdown Component
 *
 * Displays AI-generated category scores derived from published reviews
 * (Phase 3).
 *
 * The sources are shown alongside the scores rather than tucked away: the card
 * is asserting what critics thought, and a number with no way to check it is
 * indistinguishable from a number the model made up.
 *
 * Categories:
 * - Cinematography
 * - Plot
 * - Writing
 * - Characters
 * - Soundtrack
 * - Overall
 */

import React from "react";
import type { AiScoreResult, ScoreCategory } from "@shared/types/movie";

interface ScoreBreakdownProps {
  result: AiScoreResult;
}

/**
 * Configuration for each score category
 */
const CATEGORY_CONFIG: Record<
  ScoreCategory,
  {
    label: string;
    icon: string;
    description: string;
  }
> = {
  cinematography: {
    label: "Cinematography",
    icon: "🎥",
    description: "Visual style, camera work, lighting",
  },
  plot: {
    label: "Plot",
    icon: "📖",
    description: "Story structure, pacing, engagement",
  },
  writing: {
    label: "Writing",
    icon: "✍️",
    description: "Dialogue, screenplay quality",
  },
  characters: {
    label: "Characters",
    icon: "🎭",
    description: "Character depth, development, performances",
  },
  soundtrack: {
    label: "Soundtrack",
    icon: "🎵",
    description: "Music, sound design, audio",
  },
  overall: {
    label: "Overall",
    icon: "⭐",
    description: "Combined assessment",
  },
};

/**
 * Score breakdown component
 */
const ScoreBreakdown: React.FC<ScoreBreakdownProps> = ({ result }) => {
  const { scores, summary, sources } = result;

  // Order categories with "overall" last
  const orderedCategories: ScoreCategory[] = [
    "cinematography",
    "plot",
    "writing",
    "characters",
    "soundtrack",
    "overall",
  ];

  return (
    <div className="cb-space-y-3">
      <div className="cb-flex cb-items-center cb-gap-2 cb-mb-3">
        <span className="cb-text-lg">🤖</span>
        <span className="cb-text-white cb-font-medium cb-text-sm">
          AI Analysis
        </span>
        <span className="cb-text-gray-500 cb-text-xs">(beta)</span>
      </div>

      {summary && (
        <p className="cb-text-gray-300 cb-text-xs cb-leading-relaxed cb-m-0">
          {summary}
        </p>
      )}

      {orderedCategories.map((category) => {
        const score = scores[category];
        // A category the reviews didn't discuss is left out rather than
        // scored — a guessed number would read exactly like a measured one
        if (score === undefined) return null;

        return (
          <CategoryScore
            key={category}
            category={category}
            score={score}
            isOverall={category === "overall"}
          />
        );
      })}

      {sources.length > 0 && <SourceList sources={sources} />}

      {/* Disclaimer */}
      <p className="cb-text-gray-500 cb-text-xs cb-mt-3 cb-pt-2 cb-border-t cb-border-surface-lighter">
        Scores generated by AI analysis of critic and audience reviews.
        Not an official rating.
      </p>
    </div>
  );
};

/**
 * The reviews the scores were drawn from
 */
const SourceList: React.FC<{ sources: AiScoreResult["sources"] }> = ({ sources }) => (
  <div className="cb-pt-2 cb-border-t cb-border-surface-lighter">
    <p className="cb-text-gray-400 cb-text-xs cb-font-medium cb-m-0 cb-mb-1">
      Based on {sources.length} {sources.length === 1 ? "review" : "reviews"}
    </p>
    <ul className="cb-list-none cb-p-0 cb-m-0 cb-space-y-1">
      {sources.map((source) => (
        <li key={source.url}>
          <a
            href={source.url}
            target="_blank"
            rel="noopener noreferrer"
            className="cb-text-primary-400 hover:cb-text-primary-300 cb-text-xs cb-truncate cb-block"
          >
            {source.publication ?? hostnameOf(source.url)}
          </a>
        </li>
      ))}
    </ul>
  </div>
);

/**
 * Fall back to the host when a source came back without a publication name
 */
function hostnameOf(url: string): string {
  try {
    return new URL(url).hostname.replace(/^www\./, "");
  } catch {
    return url;
  }
}

/**
 * Individual category score row
 */
const CategoryScore: React.FC<{
  category: ScoreCategory;
  score: number;
  isOverall?: boolean;
}> = ({ category, score, isOverall = false }) => {
  const config = CATEGORY_CONFIG[category];
  const colorClass = getScoreColor(score);

  return (
    <div
      className={`cb-flex cb-items-center cb-gap-3 ${
        isOverall ? "cb-pt-2 cb-border-t cb-border-surface-lighter" : ""
      }`}
    >
      {/* Icon */}
      <span className="cb-text-base" title={config.description}>
        {config.icon}
      </span>

      {/* Label and bar */}
      <div className="cb-flex-1">
        <div className="cb-flex cb-items-center cb-justify-between cb-mb-1">
          <span
            className={`cb-text-xs ${
              isOverall ? "cb-text-white cb-font-medium" : "cb-text-gray-400"
            }`}
          >
            {config.label}
          </span>
          <span className={`cb-text-sm cb-font-bold ${colorClass}`}>
            {score.toFixed(1)}
          </span>
        </div>

        {/* Score bar */}
        <div className="cb-w-full cb-h-1.5 cb-bg-surface-lighter cb-rounded-full cb-overflow-hidden">
          <div
            className={`cb-h-full cb-rounded-full cb-transition-all ${colorClass.replace(
              "cb-text-",
              "cb-bg-"
            )}`}
            style={{ width: `${(score / 10) * 100}%` }}
          />
        </div>
      </div>
    </div>
  );
};

/**
 * Get color class based on score (0-10 scale)
 */
function getScoreColor(score: number): string {
  if (score >= 7.5) {
    return "cb-text-green-400";
  } else if (score >= 5) {
    return "cb-text-yellow-400";
  } else {
    return "cb-text-red-400";
  }
}

export default ScoreBreakdown;
